name: My first CI Pipeline

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: action/checkout@v4
      - name: Display Repository Files
        run: ls -la

      - name: Print success Message
        run: echo "CI Pipeline executed successfully"
